name: Maven Release

on:
  workflow_call:
    inputs:
      nexus_host_url:
        required: true
        type: string
      version:
        required: true
        type: string
      version_increment_type:
        required: true
        description: "What part of the version to increment: major, minor, or patch"
        type: string
      java_distribution:
        type: string
        required: true
      java_version:
        type: string
        required: true
      local_runner:
        type: string
        required: true

    secrets:
      nexus_username:
        required: true
      nexus_password:
        required: true
      github_ssh_key:
        required: true

jobs:

  maven_release:
    name: Maven ${{ inputs.version_increment_type }} Release version ${{ inputs.version }}
    runs-on: ${{ inputs.local_runner }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.java_distribution }}
          java-version: ${{ inputs.java_version }}
          cache: 'maven'

      - name: Maven Settings XML File
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: '[{ "id": "litteranexus", "url": "${{ inputs.nexus_host_url }}", "releases": { "enabled": true }, "snapshots": { "enabled": true } }]'
          plugin_repositories: '[{ "id": "litteranexus", "url": "${{ inputs.nexus_host_url }}", "releases": { "enabled": true }, "snapshots": { "enabled": true } }]'
          servers: '[{ "id": "litteranexus", "username": "${{ secrets.nexus_username }}", "password": "${{ secrets.nexus_password }}" }]'
          active_profiles: '[ "github" ]'
          output_file: /home/runner/.m2/settings.xml

      - name: Get Project Info
        id: get-project-info
        run: |
          NAME=$(./mvnw -ntp help:evaluate -Dexpression=project.name -q -DforceStdout)
          echo "NAME=$NAME" >> $GITHUB_OUTPUT

      - name: Prep SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.github_ssh_key }}

      - name: Maven Release Patch
        if: ${{ inputs.version_increment_type == 'patch' }}
        run: |
          git config --global user.name 'Littera GitHub'
          git config --global user.email 'littera-github@litteraeducation.com'
          ./mvnw -ntp --batch-mode build-helper:parse-version release:prepare -DscmCommentPrefix="[skip ci][maven-release-plugin] " -DdevelopmentVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT -DreleaseVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion} -Darguments='-Dmaven.test.skip=true -Dmaven.javadoc.skip=true' release:perform

      - name: Maven Release Minor
        if: ${{ inputs.version_increment_type == 'minor' }}
        run: |
          git config --global user.name 'Littera GitHub'
          git config --global user.email 'littera-github@litteraeducation.com'
          ./mvnw -ntp --batch-mode build-helper:parse-version release:prepare -DscmCommentPrefix="[skip ci][maven-release-plugin] " -DdevelopmentVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.0-SNAPSHOT -DreleaseVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion} -Darguments='-Dmaven.test.skip=true -Dmaven.javadoc.skip=true' release:perform

      - name: Maven Release Major
        if: ${{ inputs.version_increment_type == 'major' }}
        run: |
          git config --global user.name 'Littera GitHub'
          git config --global user.email 'littera-github@litteraeducation.com'
          ./mvnw -ntp --batch-mode build-helper:parse-version release:prepare -DscmCommentPrefix="[skip ci][maven-release-plugin] " -DdevelopmentVersion=\${parsedVersion.nextMajorVersion}.0.0-SNAPSHOT -DreleaseVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion} -Darguments='-Dmaven.test.skip=true -Dmaven.javadoc.skip=true' release:perform

      - name: Cache github pages
        id: cache-github-pages
        uses: actions/cache@v3
        with:
          path: target/docs
          key: ${{ steps.get-project-info.outputs.NAME }}-${{ inputs.version }}-github-pages

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        if: steps.cache-github-pages.outputs.cache-hit == 'true'
        with:
          branch: gh-pages
          target-folder: ${{ inputs.version }}
          folder: target/docs

      - name: Cache Dockerfile
        id: cache-dockerfile
        uses: actions/cache@v3
        with:
          path: Dockerfile
          key: ${{ steps.get-project-info.outputs.NAME }}-${{ inputs.version }}-dockerfile
