name: Promote image to an environment-v2

on:
  workflow_call:
    inputs:
      environment:
        type: "string"
        description: "Target environment"
        default: "dev"
      image_version:
        type: "string"        
        description: "Image version"
        required: true
      eks_config_branch:
        type: "string"        
        description: "The branch in 'littera-eks-config' to pull EKS yaml configs. Leave as 'develop'."
        required: true
        default: "develop"
      target_config:
        type: "string"
        description: "Relevant only for EKS cluster migrations"
        default: "default"
        required: true

    secrets:
      token_mvn_repo:
        required: true

jobs:

  export_vars_to_outputs:
    uses: Littera-Education/littera-github-actions/.github/workflows/export-vars.yml@v8-latest
    with:
      environment: ${{ inputs.environment }}
      target_config: ${{ inputs.target_config }}
      service_repo: ${{ github.repository }}
    secrets:
      repo_token: ${{ secrets.TOKEN_MVN_REPO }}
  
  deploy_to_environment:
    needs:
      - export_vars_to_outputs
    uses: Littera-Education/littera-github-actions/.github/workflows/eks-deploy-v2.yml@v8-latest
    with:
      image_version: ${{ inputs.image_version }}
      environment: ${{ inputs.environment }}
      cluster_name: ${{ needs.export_vars_to_outputs.outputs.cluster_name }}
      service_name: ${{ needs.export_vars_to_outputs.outputs.service_name }}
      eks_config_branch: ${{ inputs.eks_config_branch }}
      aws_account_id: ${{  needs.export_vars_to_outputs.outputs.aws_account_id }}
      kubctl_download_url: ${{ needs.export_vars_to_outputs.outputs.kubctl_download_url }}
      iam_role: ${{ needs.export_vars_to_outputs.outputs.iam_role }}
      github_actions_deploy_timeout: ${{ needs.export_vars_to_outputs.outputs.github_actions_deploy_timeout }}
      local_runner: ${{ needs.export_vars_to_outputs.outputs.local_runner }}
    secrets:
      repo_token: ${{ secrets.TOKEN_MVN_REPO }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
